# Загрузка предустановленных очередей и пользователей
load_definitions = /etc/rabbitmq/rabbitmq_definitions.json

    # Включаем встроенный сборщик метрик в формате Prometheus
    prometheus.tcp.port = 15692

    # Настройка логирования: логи в stdout для Promtail
    log.console = true
    log.console.level = info
    # RabbitMQ должен слушать все доступные интерфейсы
    listeners.tcp.default = 5672
    management.tcp.port = 15672